/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carOwner;

import config.dbConnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sheila mae albarando
 */
public class carOwnerUpdateRate extends javax.swing.JFrame {

    /**
     * Creates new form carOwnerUpdateRate
     */
    public carOwnerUpdateRate() {
        initComponents();
        displayData();
    }
    
    public void displayData(){
        try{
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT * FROM tbl_car");
            table_car.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        updatedRate = new javax.swing.JTextField();
        carID = new javax.swing.JTextField();
        updateRate = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        previousRate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_car = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        updatedRate.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.add(updatedRate);
        updatedRate.setBounds(40, 210, 240, 40);

        carID.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.add(carID);
        carID.setBounds(40, 50, 240, 40);

        updateRate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updateRate.setText("Update Rate");
        updateRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRateActionPerformed(evt);
            }
        });
        jPanel2.add(updateRate);
        updateRate.setBounds(180, 290, 103, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(40, 290, 110, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Enter Updated Rate");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 250, 240, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" Enter Car ID");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 90, 240, 40);

        previousRate.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.add(previousRate);
        previousRate.setBounds(40, 130, 240, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" Enter Previous Rate");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 170, 240, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(510, 0, 320, 380);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        table_car.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_carMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_car);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 510, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        carOwnerRegistrationCar corc = new carOwnerRegistrationCar();
        corc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updateRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRateActionPerformed
        // TODO add your handling code here:
        dbConnector dbc = new dbConnector();
        if (dbc.insertData("INSERT INTO tbl_car (c_id, c_rate, c_rate) VALUES ('" + carID + "', '" + previousRate +"','"+updatedRate+ "')")) {
            JOptionPane.showMessageDialog(null, "Car Rate Updated Successfully..!");
            // Clear GUI fields after successful insertion
            carID.setText("");
            previousRate.setText("");
            updatedRate.setText("");
            if (carID.getText().isEmpty() || previousRate.getText().isEmpty() || updatedRate.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill in all required data.");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Updating The Rate Failed...!");
        }
    }//GEN-LAST:event_updateRateActionPerformed

    private void table_carMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_carMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table_carMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carOwnerUpdateRate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carOwnerUpdateRate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carOwnerUpdateRate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carOwnerUpdateRate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new carOwnerUpdateRate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField carID;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField previousRate;
    private javax.swing.JTable table_car;
    private javax.swing.JButton updateRate;
    private javax.swing.JTextField updatedRate;
    // End of variables declaration//GEN-END:variables
}
