/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carOwner;

import config.dbConnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sheila mae albarando
 */
public class carOwnerRegistrationCar extends javax.swing.JFrame {

    /**
     * Creates new form carOwnerRegistrationCar
     */
    public carOwnerRegistrationCar() {
        initComponents();
        displayData();
    }
    
    public void displayData(){
        try{
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT * FROM tbl_car");
            table_car.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());
        
        }
    }
    
    public static String plate;
    
    public boolean carInfoDuplicateCheck(){
        
        dbConnector dbc = new dbConnector();
        
        try{
            String sql = "SELECT * FROM tbl_car WHERE c_plateNo. = '"+plateNo.getText()+"'";
            ResultSet rs = dbc.getData(sql);
            
            if(rs.next()){
                plate = rs.getString("c_plateNo.");
                if(plate.equals(plateNo.getText())){
                    JOptionPane.showMessageDialog(null, "Plate Number is Already Used.");
                    plateNo.setText("");
                }
                return true;
            }else{
                return false;
            }
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_car = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        brand = new javax.swing.JTextField();
        plateNo = new javax.swing.JTextField();
        model = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        color = new javax.swing.JTextField();
        capacity = new javax.swing.JTextField();
        rate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addCarData = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        table_car.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_carMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_car);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(10, 0, 560, 480);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, 60, 570, 490);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        brand.setForeground(new java.awt.Color(0, 0, 204));
        brand.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(brand);
        brand.setBounds(10, 10, 240, 30);

        plateNo.setForeground(new java.awt.Color(0, 0, 204));
        plateNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(plateNo);
        plateNo.setBounds(10, 370, 240, 30);

        model.setForeground(new java.awt.Color(0, 0, 204));
        model.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(model);
        model.setBounds(10, 70, 240, 30);

        type.setForeground(new java.awt.Color(0, 0, 204));
        type.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(type);
        type.setBounds(10, 130, 240, 30);

        color.setForeground(new java.awt.Color(0, 0, 204));
        color.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(color);
        color.setBounds(10, 190, 240, 30);

        capacity.setForeground(new java.awt.Color(0, 0, 204));
        capacity.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(capacity);
        capacity.setBounds(10, 250, 240, 30);

        rate.setForeground(new java.awt.Color(0, 0, 204));
        rate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(rate);
        rate.setBounds(10, 310, 240, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText(" Car Brand");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 40, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText(" Car Model");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 100, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText(" Car Type");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 160, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText(" Car Color");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 220, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText(" Car Capacity");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 280, 140, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText(" Car Rate");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 340, 140, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText(" Car Plate No.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 400, 130, 30);

        addCarData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addCarData.setText("Add Car Data");
        addCarData.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addCarData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarDataActionPerformed(evt);
            }
        });
        jPanel1.add(addCarData);
        addCarData.setBounds(140, 410, 110, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Back");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 450, 90, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Update Rate");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 450, 110, 30);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(570, 60, 260, 490);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(" Car Owner's Car Registration Form");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(0, 0, 810, 40);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(10, 10, 810, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addCarDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarDataActionPerformed
        // Check if all required fields are filled
        if (brand.getText().isEmpty() || model.getText().isEmpty() || type.getText().isEmpty() || color.getText().isEmpty() || capacity.getText().isEmpty() || rate.getText().isEmpty() || plateNo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all required data.");
        }else if(carInfoDuplicateCheck()){    
            System.out.println("Duplicated Exist");
        } else {
            // Retrieve data from GUI components 
            brand.getText();
            model.getText();
            type.getText();
            color.getText();
            capacity.getText();
            rate.getText();
            plateNo.getText();
        
            // Attempt to insert data into the database
            dbConnector dbc = new dbConnector();
        
            if (dbc.insertData("INSERT INTO tbl_car (c_brand, c_model, c_type, c_color, c_capacity, c_rate, c_plateNo.) VALUES ('" + brand + "', '" + model + "', '" + type + "', '" + color+ "', '" + capacity + "', '" + rate + "', '" + plateNo + "')")) {
                JOptionPane.showMessageDialog(null, "Car Information Inserted Successfully!");
                // Clear GUI fields after successful insertion
                brand.setText("");
                model.setText("");
                type.setText("");
                color.setText("");
                capacity.setText("");
                rate.setText("");
                plateNo.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to insert car information. Connection error or invalid data.");
            }
        }
    }//GEN-LAST:event_addCarDataActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        carOwnerDashboard cod = new carOwnerDashboard();
        cod.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void table_carMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_carMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table_carMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        carOwnerUpdateRate cour = new carOwnerUpdateRate();
        cour.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carOwnerRegistrationCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carOwnerRegistrationCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carOwnerRegistrationCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carOwnerRegistrationCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new carOwnerRegistrationCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCarData;
    private javax.swing.JTextField brand;
    private javax.swing.JTextField capacity;
    private javax.swing.JTextField color;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField model;
    private javax.swing.JTextField plateNo;
    private javax.swing.JTextField rate;
    private javax.swing.JTable table_car;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
